project:
  type: book
  
execute:
  cache: false
#  freeze: auto  # re-render only when source changes

book:
  title: "의학통계학"
  author: "이용희"
  date: last-modified
  date-format: YYYY-MM-DD, A hh 시
#  repo-url: https://github.com/ilovedata/statmehods
  downloads: [pdf]
  chapters:
    - index.qmd
    - notes/intro.qmd
    - part: "분할표와 연관성"
      chapters:
        - notes/association.qmd
        - notes/association-test.qmd
        - notes/diagnose.qmd
    - part: "집단의 비교"
      chapters:
        - notes/anova.qmd
        - notes/ancova.qmd
        - notes/multiple.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    lang: ko 
    language: custom.yml
    code-fold: false
    code-overflow: wrap
    embed-resources: false
    toc: true
    toc-depth: 3
    number-depth: 3
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    fig-cap-location: top
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix: "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    css: styles.css
    include-in-header:
      - text: |
          <script type="text/javascript">
           window.MathJax = {
            tex: {
              macros: {
              RR: '{\\mathbb R}',                    // a simple string replacement
              hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
              bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
              pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
              pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2]
            },
            environments: {
            braced: ["\\left\\{", "\\right\\}"]
            }
           }
          };
          </script>
#    include-in-header:
#      - latex/preamble-mathjax.tex
  pdf:
    documentclass: scrbook
    classoption: oneside
    papersize: A4
# 오류 발생     lang: ko
    fontsize: 11pt
    lof: true
    lot: true
    code-overflow: wrap
    language: custom.yml
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix:  "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header: latex/preamble.tex