\mainmatter

# 서론 {#intro}

이 교과서는 의학연구와 생명과학에 관련된 연구에서 사용되는 다양한 통계적 방법들의 이론과 응용을 살펴보기 위한 것입니다.

이 교과서에서는 다음과 같은 주제를 다룰 것입니다.

- 연관성의 검정 
- 검정 및 평가	
- 분산분석과 공분산분석
- 로지스틱 회귀분석		
- 반복측정자료
- 생존분석
- 임상시험연구의 개념 및 설계
- 실험 대상자수의 결정			

## 공정한 실험 

20세기가 시작되면서 통계적 방법은 모든 과학분야의 연구에 적용되고 있습니다. 현대과학은 공정하고 합리적인 실험(또는 관측연구)에서 나오는 결론을 선호합니다. 이를 증거에 기반한 연구(evidence-based research)라고 합니다. 

증거에 기반한 연구를 수행하려면 공정한 실험을 수행할 수 있는 구체적인 방법을 결정해야 합니다. 또한 실험 대상자의 수와 자료를 분석하는 방법도 적절하게 정해야 합니다. 즉 실험을 계획하는 방법이 매우 중요합니다.

그럼 공정하고 합리적인 실험은 어떤 것일까요? 이러한 질문에 대하여 실험을 수행할 때 발생할 수 있는 공정하지 않고 비합리적인 요소가 무었인지 찾아보면 답이 나오게 됩니다.

이 과목을 수강할 떄  여러분은 이러한 질문을 수시로 던지면서 생각해 보기를 강력하게 추천합니다. 

## 의학연구의 특성  

사람을 대상으로 하는 의학연구, 즉 우리가 흔히 임살실험(clinical trial)이라고 부르는 실험들은 편향이 발생할 수 있는 여러 가지 요인를 제거하기 위하여 매우 정교하게 설계됩니다. 

사실 의학연구에서 통계학자의 가장 중요한 역활은 자료의 분석이 아니라 실험의 계획과 수행에 있습니다. 물론 다양한 방법을 사용하여 유용한 결론을 이끌어 내는 탐색적인 연구에서는 주어진 자료를 분석하는 능력도 매우 중요합니다. 하지만 치료법의 효과와 안전성을 확인하는 주요한 임상실험에서는 실험을 적절하고 효과적으로 계획하는 능력이 더 중요합니다.


통상적으로 중요한 임상실험은  그 특성 상 **연구을 시작하게 되면** 최종 분석에 사용될 주요 변수를 바꿀수 없을 뿐만 아니라 실험의 방법과 대상자의 수도 원칙적으로 변경할 수 없습니다.
이렇게 실험을 수행할 때 강력한 제한을 두는 것은 실험에서 발생할 수 있는 여러가지 편향(bias)를 줄이기 위한 것입니다. 또한 유리한 실험만 선택하여 사용하거나 실험이 처리(treatment)외의 다른 요인에 의하여 영향을 받는 것을 차단하기 위해서입니다.  


## 통계적 주제 

예를 들어서 최근에 유행하고 있는 코로나 19에 대한 치료제의 효과와 안전성을 확인하는 임상실험을 상상해 봅시다. 이런 임상실험을 수행하기 위해서는 실험의 시작부터 종료까지 어떤 절차를 거쳐야 하며 긱 절차마다 수행해야할 작업은 무었을까요? 또한 실험이 종료되면 수집한 자료들은 어떻게 분석해야 할까요? 

임상실험을 계획하는 경우 통계학자의 입장에서 중요하게 고려해야할 사항은 다음과 같습니다.

- 사용할 실험 방법은 무었인가? 
- 실험에 참가하는 환자들을 어떻게 치료 집단(treatment groups)에 배정해야 하는가? 
- 얼마나 많은 환자들이 실험에 참가해야 하는가? 
- 실험에서 수집되는 자료들은 어떤 특성을 가지는가?
- 실험에서 수집된 자료를 어떤 방법을 적용하여 분석해야 하는가?


## 강의의 구성 

이 과목에서는 먼저  의학과 생명과학의 연구에서 수집된 자료를 분석할 수 있는 통계적 방법들은 배울 것입니다. 이러한 통계적 방법들은 주로 통계적 가설검정(statistical hypothesis tesing)과 선형모형(linear model) 또는 회귀모형(regression model)에 의거한 방법들입니다.   

두번째로 배우게 될 내용을 임상시험에서 사용되는 실험계획에 관련된  개념과 방법들입니다. 임의화(randomization)이 왜 실험에서 중요한 개념인지를 배울 것입니다. 유의수준과 검정력에 기반하여 실험 대상자의 수를 산정하는 법을 배울 것입니다. 또한 임상실험에서 사용되는 다양한 계획법에 대한여 배울것 입니다.

